[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Smart Buildings: The Role of Intelligent Technologies in Designing Sustainable and Energy-Efficient Buildings"
